name: Mirror and run GitLab CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "git@gitlab.com:yann.pomie/dosm.git"
          ssh_username: ${{ secrets.GITLAB_USERNAME }}
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
