name: Mirror and run GitLab CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.polytech.umontpellier.fr/yann.pomie/dosm"
      env:
        GITLAB_HOSTNAME: "https://gitlab.polytech.umontpellier.fr"
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: 1730
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
